import type { Metadata } from "next";
import { Mail, MapPin, MessageCircle, Phone, ShieldCheck } from "lucide-react";
import EssentialPageShell, { InlinePageLink, PageLink } from "@/components/EssentialPageShell";

export const metadata: Metadata = { title: "Contact ReplacementPlates | ReplacementPlates", description: "Email, call or WhatsApp ReplacementPlates about your order, documents or collection." };

export default function ContactPage() {
  return (
    <EssentialPageShell eyebrow="We’re here to help" title="Contact ReplacementPlates" intro="The quickest way to reach us is by WhatsApp or telephone. You can also email us. Please include your order number if you have one." image="/images/reasons/trailer.jpg">
      <div className="grid gap-4 lg:grid-cols-[.9fr_1.1fr]">
        <section className="rounded-3xl bg-[#0b1625] p-5 text-white shadow-xl sm:p-7"><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#f3c544]">Get in touch</p><h2 className="mt-2 text-2xl font-black tracking-[-.04em]">Choose the quickest route.</h2><div className="mt-5 space-y-2">{[[Mail, "Email", "info@replacementplates.uk", "mailto:info@replacementplates.uk"], [MessageCircle, "WhatsApp", "+44 7754 185366", "https://wa.me/447754185366"], [Phone, "Telephone", "020 3576 6603", "tel:02035766603"], [MapPin, "Post", "Private Number Plate Maker Ltd, Stand 53, New Spitalfields Market, London, E10 5SQ", "#post"]].map(([Icon, label, value, href]) => <a key={label as string} href={href as string} className="flex items-start gap-3 rounded-2xl border border-white/10 bg-white/[.05] p-3 transition hover:border-[#f3c544]/40 hover:bg-white/[.08]"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-[#f3c544]/15 text-[#f3c544]"><Icon className="h-3.5 w-3.5" /></span><span><span className="block text-[10px] font-black uppercase tracking-[.14em] text-slate-500">{label as string}</span><span className="mt-1 block text-xs font-semibold text-slate-200">{value as string}</span></span></a>)}</div><p className="mt-5 text-xs leading-5 text-slate-400">A photo helps if a plate is damaged or wrong, but it is not required.</p></section>
        <section className="rounded-3xl border border-white/80 bg-white/75 p-5 shadow-[0_16px_40px_rgba(15,23,42,.07)] sm:p-7"><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#c89612]">Before you message</p><h2 className="mt-2 text-2xl font-black tracking-[-.04em]">A few useful answers.</h2><div className="mt-5 space-y-4"><div><h3 className="text-base font-black">Collecting your plates</h3><p className="mt-1.5 text-sm leading-6 text-slate-600">Our collection location is <strong className="text-slate-950">Castleview Gardens, Ilford, IG1 3QF</strong>. Ready within 3 hours, subject to WhatsApp confirmation. Please confirm before travelling. See <InlinePageLink href="/areas-we-cover">areas we cover</InlinePageLink>.</p></div><div className="border-t border-slate-200 pt-4"><h3 className="text-base font-black">Cancelling an order</h3><p className="mt-1.5 text-sm leading-6 text-slate-600">You can cancel for a full refund at any time before production starts. No cancellation or administration fee applies. See <InlinePageLink href="/returns">returns and cancellations</InlinePageLink>.</p></div><div className="border-t border-slate-200 pt-4"><h3 className="text-base font-black">Making a complaint</h3><p className="mt-1.5 text-sm leading-6 text-slate-600">Tell us by email, WhatsApp, telephone or post. We’ll acknowledge your complaint, look into it and tell you what we can do. See our <InlinePageLink href="/terms">terms</InlinePageLink>.</p></div></div></section>
      </div>
      <section id="post" className="mt-4 grid gap-4 sm:grid-cols-2"><div className="rounded-3xl border border-white/80 bg-white/75 p-5 shadow-sm sm:p-6"><ShieldCheck className="h-5 w-5 text-[#c89612]" /><h2 className="mt-4 text-lg font-black">Data protection requests</h2><p className="mt-2 text-sm leading-6 text-slate-600">To ask about or exercise your rights over your personal data, contact us using the details above. See our <InlinePageLink href="/privacy">privacy policy</InlinePageLink>.</p></div><div className="rounded-3xl border border-[#f3c544]/30 bg-[#f3c544]/10 p-5 shadow-sm sm:p-6"><h2 className="text-lg font-black">Need help ordering?</h2><p className="mt-2 text-sm leading-6 text-slate-700">If you need help placing an order, see our accessibility information or contact us directly.</p><div className="mt-4 flex flex-wrap gap-2"><PageLink href="/accessibility">Accessibility</PageLink><PageLink href="/how-it-works" light>How it works</PageLink></div></div></section>
    </EssentialPageShell>
  );
}
