import type { Metadata } from "next";
import { Clock3, MapPin, PackageCheck, ShieldAlert, Truck } from "lucide-react";
import EssentialPageShell, { InlinePageLink, PageLink } from "@/components/EssentialPageShell";

export const metadata: Metadata = { title: "Delivery and Dispatch | ReplacementPlates", description: "Royal Mail First Class is £3 on orders under £15 and free from £15. Tracked 24 is an additional £2. How dispatch, delivery and collection timings work." };

export default function DeliveryPage() {
  return <EssentialPageShell eyebrow="Royal Mail delivery or Ilford collection" title="Delivery and Dispatch" intro="See the delivery rate before you pay, understand when we aim to dispatch, or choose confirmed collection from Ilford." image="/images/hero-car-bg.jpg">
    <section className="grid gap-3 md:grid-cols-2"><article className="rounded-[1.75rem] bg-[#080c14] p-5 text-white shadow-xl sm:p-7"><Truck className="h-5 w-5 text-[#f3c544]" /><p className="mt-4 text-[10px] font-black uppercase tracking-[.17em] text-[#f3c544]">Royal Mail First Class</p><h2 className="mt-1 text-2xl font-black tracking-[-.04em]">Free from £15.</h2><p className="mt-3 text-sm leading-6 text-slate-300">£3 on goods orders under £15, and free on orders of £15 or more. Exactly £15 qualifies for free First Class delivery.</p><div className="mt-5 rounded-2xl border border-white/10 bg-white/[.06] p-4"><span className="text-[10px] font-black uppercase tracking-[.14em] text-slate-400">Delivery aim</span><p className="mt-1 text-sm font-semibold">Next working day, including Saturday — an aim, not a guarantee.</p></div></article><article className="rounded-[1.75rem] border border-[#f3c544]/30 bg-[#f3c544]/10 p-5 sm:p-7"><PackageCheck className="h-5 w-5 text-[#9a7410]" /><p className="mt-4 text-[10px] font-black uppercase tracking-[.17em] text-[#9a7410]">Royal Mail Tracked 24</p><h2 className="mt-1 text-2xl font-black tracking-[-.04em]">A £2 upgrade.</h2><p className="mt-3 text-sm leading-6 text-slate-700">£5 total delivery charge under £15, or £2 total delivery charge from £15. Tracking is optional and shown separately before you pay.</p><div className="mt-5 rounded-2xl bg-white/70 p-4"><span className="text-[10px] font-black uppercase tracking-[.14em] text-[#9a7410]">Delivery aim</span><p className="mt-1 text-sm font-semibold">Next working day with tracking, subject to Royal Mail’s service terms.</p></div></article></section>

    <section className="mt-4 overflow-hidden rounded-[1.75rem] border border-white/90 bg-white/80 shadow-[0_20px_55px_rgba(15,23,42,.07)]"><div className="px-5 pb-4 pt-5 sm:px-7 sm:pt-7"><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#c89612]">Three different moments</p><h2 className="mt-1 text-2xl font-black tracking-[-.04em]">Dispatch, delivery and collection.</h2></div><div className="grid border-t border-slate-200 md:grid-cols-3">{[["01", "Dispatch", "When we hand your parcel to Royal Mail."], ["02", "Delivery", "When Royal Mail brings it to you."], ["03", "Collection", "When you pick up your plates from us."]].map(([number, title, text], index) => <div key={title} className={`p-5 sm:p-7 ${index ? "border-t border-slate-200 md:border-l md:border-t-0" : ""}`}><span className="text-3xl font-black tracking-[-.07em] text-[#f3c544]">{number}</span><h3 className="mt-5 text-xl font-black tracking-[-.035em]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>)}</div></section>

    <section className="mt-4 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><article className="rounded-[1.75rem] border border-white/90 bg-white/75 p-5 sm:p-7"><Clock3 className="h-5 w-5 text-[#c89612]" /><p className="mt-4 text-[10px] font-black uppercase tracking-[.17em] text-[#c89612]">When we aim to dispatch</p><h2 className="mt-1 text-2xl font-black tracking-[-.04em]">Complete before 2pm on a weekday.</h2><p className="mt-3 text-sm leading-6 text-slate-600">Your order and document checks must both be complete before 2pm, Monday to Friday, for us to aim to dispatch it the same day. Later or weekend completion does not have a same-day dispatch aim.</p><div className="mt-5 space-y-3 border-t border-slate-200 pt-5 text-sm leading-6 text-slate-600"><p><strong className="text-slate-950">Monday–Thursday:</strong> we aim to dispatch that day; Royal Mail then aims for the next working day.</p><p><strong className="text-slate-950">Friday:</strong> First Class includes Saturday delivery, but we do not promise a Saturday or Monday arrival.</p><p><strong className="text-slate-950">Bank holidays:</strong> allow extra time, as Royal Mail does not normally deliver on them.</p></div><p className="mt-5 text-xs leading-5 text-slate-500">A missing or unclear document, or a registration that does not match vehicle evidence, can delay checks. See <InlinePageLink href="/documents-you-need">documents you need</InlinePageLink>.</p></article><article className="rounded-[1.75rem] bg-slate-950 p-5 text-white shadow-xl sm:p-7"><MapPin className="h-5 w-5 text-[#f3c544]" /><p className="mt-4 text-[10px] font-black uppercase tracking-[.17em] text-[#f3c544]">Collecting instead</p><h2 className="mt-1 text-2xl font-black tracking-[-.04em]">Confirmed collection in Ilford.</h2><p className="mt-3 text-sm leading-6 text-slate-300">Castleview Gardens, Ilford, IG1 3QF. Ready within 3 hours, subject to WhatsApp confirmation. Please confirm before travelling.</p><p className="mt-4 text-xs leading-5 text-slate-400">Collection readiness is separate from dispatch timing and not tied to the 2pm cut-off. There is no delivery charge when you collect.</p><div className="mt-5 flex flex-wrap gap-2"><PageLink href="/areas-we-cover">Areas we cover</PageLink><a href="https://wa.me/447754185366" className="inline-flex items-center justify-center rounded-full border border-white/20 px-4 py-2.5 text-xs font-bold text-white">Confirm collection</a></div></article></section>

    <section className="mt-4 rounded-[1.75rem] border border-[#f3c544]/30 bg-[#f3c544]/10 p-5 sm:p-7"><div className="flex gap-4"><ShieldAlert className="mt-1 h-5 w-5 shrink-0 text-[#9a7410]" /><div><h2 className="text-xl font-black tracking-[-.035em]">If something goes wrong</h2><p className="mt-2 text-sm leading-6 text-slate-700">If your parcel is late, missing or damaged, contact us with your order number. A photo of the parcel and plate helps if you can take one. We’ll look into it with Royal Mail. Plates stay at our risk until delivery or collection.</p><p className="mt-3 text-xs leading-5 text-slate-600">We deliver to Great Britain. For Northern Ireland, the Channel Islands or the Isle of Man, <InlinePageLink href="/contact">contact us before ordering</InlinePageLink>. Read <InlinePageLink href="/returns">returns and cancellations</InlinePageLink>, <InlinePageLink href="/warranty">warranty and faulty plates</InlinePageLink>, or the guides on <InlinePageLink href="/guides/sameday-dispatch-vs-nextday-delivery">same-day dispatch</InlinePageLink> and <InlinePageLink href="/guides/replacement-number-plate-delivery-and-packaging">delivery and packaging</InlinePageLink>.</p></div></div></section>
  </EssentialPageShell>;
}
