import type { Metadata } from "next";
import { Clock3, MapPin, MessageCircle, Send } from "lucide-react";
import EssentialPageShell, { InlinePageLink, PageLink } from "@/components/EssentialPageShell";

export const metadata: Metadata = { title: "Areas We Cover | ReplacementPlates", description: "Where ReplacementPlates delivers and where you can collect. One collection location in Ilford, East London; Royal Mail delivery." };

const regions = [
  ["Midlands", ["Birmingham", "Coventry", "Leicester", "Nottingham", "Derby", "Northampton", "Stoke-on-Trent"]],
  ["North of England", ["Manchester", "Liverpool", "Leeds", "Sheffield", "Newcastle upon Tyne"]],
  ["South and South West", ["Bristol", "Southampton", "Portsmouth", "Luton", "Milton Keynes"]],
  ["East of England", ["Cambridge", "Peterborough", "Ipswich", "Norwich"]],
  ["Scotland", ["Glasgow", "Edinburgh", "Aberdeen", "Dundee"]],
  ["Wales", ["Cardiff", "Swansea", "Newport, Wales"]],
] as const;

const nearby = ["Ilford", "London", "Barking", "Dagenham", "Romford", "Seven Kings", "Goodmayes", "Redbridge", "East Ham", "Stratford"];

export default function AreasWeCoverPage() {
  return <EssentialPageShell eyebrow="Delivery across Great Britain" title="Areas We Cover" intro="Royal Mail delivery is available across Great Britain. Our single collection location is in Ilford, East London." image="/images/reasons/trailer.jpg">
    <section className="relative overflow-hidden rounded-[1.75rem] bg-[#080c14] p-5 text-white shadow-xl sm:p-8"><div className="pointer-events-none absolute -right-16 -top-16 h-64 w-64 rounded-full bg-[#f3c544]/15 blur-3xl" /><div className="relative grid gap-6 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><span className="flex h-11 w-11 items-center justify-center rounded-2xl border border-[#f3c544]/25 bg-[#f3c544]/10 text-[#f3c544]"><MapPin className="h-5 w-5" /></span><p className="mt-5 text-[10px] font-black uppercase tracking-[.17em] text-[#f3c544]">Collection in East London</p><h2 className="mt-1 text-3xl font-black tracking-[-.05em]">One confirmed collection point.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300"><strong className="text-white">Castleview Gardens, Ilford, IG1 3QF.</strong> Plates are ready within 3 hours, subject to WhatsApp confirmation. Please confirm before travelling.</p><div className="mt-5 flex flex-wrap gap-2">{nearby.map((area) => <span key={area} className="rounded-full border border-white/10 bg-white/[.06] px-3 py-1.5 text-xs font-semibold text-slate-300">{area}</span>)}</div></div><aside className="rounded-3xl border border-white/10 bg-white/[.06] p-5"><Clock3 className="h-5 w-5 text-[#f3c544]" /><h3 className="mt-4 text-lg font-black">Collection checklist</h3><ul className="mt-4 space-y-3 text-sm leading-5 text-slate-300"><li>Contact us by WhatsApp to confirm same-day collection.</li><li>Wait for confirmation before travelling.</li><li>We’ll tell you what to bring when we confirm.</li></ul><a href="https://wa.me/447754185366" className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#f3c544] px-4 py-2.5 text-xs font-bold text-slate-950"><MessageCircle className="h-3.5 w-3.5" /> Confirm on WhatsApp</a></aside></div></section>

    <section className="mt-4 rounded-[1.75rem] border border-white/90 bg-white/80 p-5 shadow-[0_20px_55px_rgba(15,23,42,.07)] sm:p-8"><div className="flex flex-col gap-3 border-b border-slate-200 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#c89612]">Delivered by Royal Mail</p><h2 className="mt-1 text-2xl font-black tracking-[-.04em]">Across Great Britain.</h2></div><p className="max-w-md text-sm leading-6 text-slate-500">Customers outside Ilford can choose Royal Mail delivery, or arrange collection from Ilford. We do not have shops or branches elsewhere.</p></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{regions.map(([region, places], index) => <article key={region} className={`rounded-2xl p-4 ${index % 2 === 0 ? "bg-slate-950 text-white" : "border border-slate-200 bg-slate-50"}`}><Send className={`h-4 w-4 ${index % 2 === 0 ? "text-[#f3c544]" : "text-[#c89612]"}`} /><h3 className="mt-4 text-base font-black">{region}</h3><p className={`mt-2 text-sm leading-6 ${index % 2 === 0 ? "text-slate-300" : "text-slate-600"}`}>{places.join(" · ")}</p></article>)}</div><p className="mt-6 text-sm leading-6 text-slate-600">Royal Mail delivery aims do not apply in the same way to some remote areas, including parts of the Highlands and Islands of Scotland. See <InlinePageLink href="/delivery">delivery and dispatch</InlinePageLink> for charges and timing.</p></section>

    <section className="mt-4 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><article className="rounded-[1.75rem] border border-[#f3c544]/30 bg-[#f3c544]/10 p-5 sm:p-7"><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#9a7410]">Outside Great Britain</p><h2 className="mt-2 text-2xl font-black tracking-[-.04em]">Please ask before ordering.</h2><p className="mt-3 text-sm leading-6 text-slate-700">For Northern Ireland, the Channel Islands and the Isle of Man, contact us before ordering. We’ll confirm whether we can deliver to your address; please do not place an order until we have.</p><div className="mt-5 flex flex-wrap gap-2"><PageLink href="/contact">Contact us</PageLink><PageLink href="/delivery" light>Delivery details</PageLink></div></article><article className="rounded-[1.75rem] border border-white/90 bg-white/75 p-5 sm:p-7"><h2 className="text-xl font-black tracking-[-.035em]">Need a plate delivered?</h2><p className="mt-2 text-sm leading-6 text-slate-600">First Class is £3 on goods orders under £15 and free from £15. Tracked 24 is an optional £2 upgrade.</p><p className="mt-4 text-xs leading-5 text-slate-500">Delivery rates, dispatch times, and your collection option are shown before you pay.</p></article></section>
  </EssentialPageShell>;
}
