import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, CheckCircle2, Clock3, Globe2, MapPin, Truck } from "lucide-react";
import { Eyebrow } from "./_shared";

export default function DeliverySection() {
  return (
    <section id="delivery" aria-labelledby="delivery-heading" className="relative bg-[linear-gradient(180deg,#f8fafc_0%,#eef3f8_100%)] text-slate-950">
      <div className="homepage-section-content mx-auto max-w-[1280px] px-5 pb-16 pt-16 sm:px-8 sm:pt-20 lg:px-10 lg:pb-20">
        <div className="mb-6 grid gap-3 lg:grid-cols-[1fr_390px] lg:items-end lg:gap-10"><div><Eyebrow>Delivery & collection</Eyebrow><h2 id="delivery-heading" className="max-w-[690px] text-[clamp(2rem,4vw,3.35rem)] font-black leading-[1.02] tracking-[-.055em]">Get your plates where <span className="text-gradient-yellow-on-light">you need them.</span></h2></div><p className="max-w-sm text-[15px] leading-6 text-slate-500">Choose Royal Mail delivery across Great Britain, or collect from our Ilford collection point once your order is ready.</p></div>
        <div className="grid gap-3 lg:grid-cols-[1.15fr_.85fr]"><div className="grid gap-3 sm:grid-cols-2"><div className="glass-card glass-card-light rounded-3xl border border-white/80 p-4 shadow-[0_14px_36px_rgba(15,23,42,.08)] sm:p-5"><div className="flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-950 text-[#f3c544]"><Truck className="h-4 w-4" /></span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-black uppercase tracking-[.14em] text-emerald-700">UK delivery</span></div><h3 className="mt-5 text-lg font-black tracking-[-.03em]">Royal Mail delivery</h3><p className="mt-2 text-[14px] leading-5 text-slate-500">First Class is £3 under £15 and free at £15 or more. Upgrade to Tracked 24 for an additional £2.</p><div className="mt-4 flex items-start gap-2 border-t border-slate-200 pt-3 text-[12px] font-bold leading-4 text-slate-600"><Clock3 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#c89612]" /> Order before 2pm on a working weekday for same-day dispatch aim.</div></div><div className="glass-card glass-card-light rounded-3xl border border-white/80 p-4 shadow-[0_14px_36px_rgba(15,23,42,.08)] sm:p-5"><div className="flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#f3c544] text-slate-950"><MapPin className="h-4 w-4" /></span><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-black uppercase tracking-[.14em] text-amber-700">Ilford</span></div><h3 className="mt-5 text-lg font-black tracking-[-.03em]">Collect in person</h3><p className="mt-2 text-[14px] leading-5 text-slate-500">Castleview Gardens, Ilford, IG1 3QF. Please confirm with us before travelling.</p><div className="mt-4 flex items-start gap-2 border-t border-slate-200 pt-3 text-[12px] font-bold leading-4 text-slate-600"><CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-emerald-600" /> Ready within 3 hours, subject to WhatsApp confirmation.</div></div></div>
          <div className="relative min-h-[230px] overflow-hidden rounded-3xl bg-slate-950 p-5 text-white shadow-[0_18px_45px_rgba(15,23,42,.2),0_10px_28px_rgba(243,197,68,.06)] sm:p-6"><Image src="/images/hero-car-bg.jpg" alt="Car with a replacement number plate" fill className="object-cover object-[68%_55%] opacity-25" sizes="(max-width: 1024px) 100vw, 40vw" /><div className="absolute inset-0 bg-gradient-to-br from-slate-950 via-slate-950/80 to-slate-950/25" /><div className="relative"><Globe2 className="h-5 w-5 text-[#f3c544]" /><h3 className="mt-4 text-xl font-black tracking-[-.04em]">One collection point. Reliable delivery everywhere else.</h3><p className="mt-2 max-w-sm text-[14px] leading-5 text-slate-300">We do not have shops or branches elsewhere. See the full delivery areas, charges and timings before you order.</p><div className="mt-5 flex flex-wrap gap-2"><Link href="/delivery" className="group inline-flex items-center gap-1.5 rounded-full bg-[#f3c544] px-3.5 py-2 text-[11px] font-black text-slate-950">Delivery details <ArrowRight className="h-3 w-3 transition group-hover:translate-x-1" /></Link><Link href="/areas-we-cover" className="inline-flex items-center gap-1.5 rounded-full border border-white/20 px-3.5 py-2 text-[11px] font-bold text-white">Areas we cover <ArrowUpRight className="h-3 w-3" /></Link></div></div></div></div>
      </div>
    </section>
  );
}
