import Link from "next/link";
import { Mail, MessageCircle, Phone } from "lucide-react";

const footerGroups = [
  { title: "Explore", links: [["About us", "/about"], ["How it works", "/how-it-works"], ["Prices", "/prices"], ["Areas we cover", "/areas-we-cover"]] },
  { title: "Help & support", links: [["Delivery & collection", "/delivery"], ["Documents needed", "/documents-you-need"], ["FAQs", "/faqs"], ["Contact us", "/contact"]] },
  { title: "Policies", links: [["Returns & cancellations", "/returns"], ["Warranty", "/warranty"], ["Terms & conditions", "/terms"], ["Privacy policy", "/privacy"], ["Cookie policy", "/cookies"], ["Accessibility", "/accessibility"]] },
] as const;

export default function SiteFooter() {
  return <footer className="border-t border-white/10 bg-[#050912] text-white"><div className="mx-auto max-w-[1280px] px-5 py-10 sm:px-8 lg:px-10 lg:py-12"><div className="grid gap-8 lg:grid-cols-[1.15fr_1.85fr]"><div><Link href="/" className="inline-flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-[#fde9a3] to-[#c89612] text-xs font-black text-white">RP</span><span><span className="block text-sm font-bold">ReplacementPlates<span className="text-[#f3c544]">.uk</span></span><span className="mt-0.5 block text-[9px] font-medium uppercase tracking-[.16em] text-slate-500">DVLA registered · RNPS 75449</span></span></Link><p className="mt-4 max-w-[320px] text-[13px] leading-5 text-slate-400">ReplacementPlates is a trading name of Private Number Plate Maker Ltd. Made-to-order replacement number plates with Royal Mail delivery or Ilford collection.</p><div className="mt-4 space-y-1.5 text-xs text-slate-400"><a className="flex items-center gap-2 transition hover:text-white" href="mailto:info@replacementplates.uk"><Mail className="h-3.5 w-3.5 text-[#f3c544]" /> info@replacementplates.uk</a><a className="flex items-center gap-2 transition hover:text-white" href="tel:02035766603"><Phone className="h-3.5 w-3.5 text-[#f3c544]" /> 020 3576 6603</a><a className="flex items-center gap-2 transition hover:text-white" href="https://wa.me/447754185366"><MessageCircle className="h-3.5 w-3.5 text-[#f3c544]" /> WhatsApp us</a></div></div><div className="grid grid-cols-2 gap-6 sm:grid-cols-3">{footerGroups.map((group) => <div key={group.title}><h3 className="text-[10px] font-black uppercase tracking-[.16em] text-white">{group.title}</h3><ul className="mt-3 space-y-2">{group.links.map(([label, href]) => <li key={href}><Link href={href} className="text-xs text-slate-400 transition hover:text-[#f3c544]">{label}</Link></li>)}</ul></div>)}</div></div><div className="mt-8 flex flex-col gap-2 border-t border-white/10 pt-4 text-[10px] leading-4 text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} Private Number Plate Maker Ltd · Company number 16163051</p><p>Registered office: London, E10 5SQ · Collection: Ilford, IG1 3QF</p></div></div></footer>;
}
