import type { Metadata } from "next";
import { BadgeCheck, LockKeyhole, MessageCircleQuestion, UserRoundCheck } from "lucide-react";
import EssentialPageShell, { PageLink } from "@/components/EssentialPageShell";
import PublicationMarkdown from "@/components/PublicationMarkdown";

export const metadata: Metadata = { title: "Privacy Policy | ReplacementPlates", description: "How Private Number Plate Maker Ltd, trading as ReplacementPlates, uses personal information and how to exercise privacy rights or complain." };

export default function PrivacyPage() {
  return <EssentialPageShell eyebrow="Your information, explained clearly" title="Privacy Policy" intro="How Private Number Plate Maker Ltd uses personal information when you visit ReplacementPlates, place an order, provide documents or contact us." image="/images/reasons/lost.jpg">
    <section className="grid gap-3 md:grid-cols-3"><article className="rounded-[1.5rem] border border-white/90 bg-white/80 p-5 shadow-sm"><LockKeyhole className="h-5 w-5 text-[#c89612]" /><h2 className="mt-4 text-lg font-black tracking-[-.03em]">Why we collect it</h2><p className="mt-2 text-sm leading-6 text-slate-600">To check identity and entitlement, make and deliver an order, keep required records and provide support.</p></article><article className="rounded-[1.5rem] bg-[#080c14] p-5 text-white shadow-xl"><BadgeCheck className="h-5 w-5 text-[#f3c544]" /><h2 className="mt-4 text-lg font-black tracking-[-.03em]">What we do not do</h2><p className="mt-2 text-sm leading-6 text-slate-300">We do not store full card details and we do not sell your personal information.</p></article><article className="rounded-[1.5rem] border border-[#f3c544]/30 bg-[#f3c544]/10 p-5"><UserRoundCheck className="h-5 w-5 text-[#9a7410]" /><h2 className="mt-4 text-lg font-black tracking-[-.03em]">Your rights</h2><p className="mt-2 text-sm leading-6 text-slate-700">You can ask for a copy, correction, deletion in some cases, restriction, objection, portability, or withdraw consent.</p></article></section>
    <section className="mt-4 rounded-[1.75rem] border border-white/90 bg-white/75 p-5 shadow-[0_20px_55px_rgba(15,23,42,.07)] sm:p-7"><div className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#c89612]">Data protection contact</p><h2 className="mt-1 text-2xl font-black tracking-[-.04em]">Ask a question or make a request.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Email info@replacementplates.uk, use WhatsApp, telephone 020 3576 6603, or write to our registered office. We use “data protection contact” for the person who handles these requests.</p></div><PageLink href="/contact">Contact us</PageLink></div></section>
    <div className="mt-4"><PublicationMarkdown file="E09-privacy-policy.md" tone="warm" /></div>
    <section className="mt-4 rounded-[1.75rem] bg-[#080c14] p-5 text-white sm:p-7"><div className="flex gap-3"><MessageCircleQuestion className="mt-1 h-5 w-5 shrink-0 text-[#f3c544]" /><div><h2 className="text-xl font-black tracking-[-.035em]">Not happy with how we handled your data?</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Tell us by email, WhatsApp, telephone or post. We accept a complaint however you send it, acknowledge it within 30 days, keep you informed and tell you the outcome. You can also complain directly to the ICO.</p></div></div></section>
  </EssentialPageShell>;
}
