import type { Metadata } from "next";
import Link from "next/link";
import { Check, Package, ShieldCheck, Truck } from "lucide-react";
import EssentialPageShell, { InlinePageLink, PageLink } from "@/components/EssentialPageShell";

export const metadata: Metadata = { title: "Number Plate Prices | ReplacementPlates", description: "ReplacementPlates prices for one plate and for a front and rear pair, with delivery charges shown." };

const prices = [
  ["Standard", "/standard-number-plates", "£12.49", "£24.98"],
  ["3D gel", "/3d-number-plates", "£19.95", "£39.90"],
  ["4D", "/4d-number-plates", "£19.95", "£39.90"],
  ["5D (4D gel)", "/5d-number-plates", "£34.95", "£69.90"],
  ["Ghost", "/ghost-number-plates", "£34.95", "£69.90"],
  ["Bevel", "/bevel-number-plates", "£39.95", "£79.90"],
] as const;

export default function PricesPage() {
  return <EssentialPageShell eyebrow="Clear, per-plate pricing" title="Number Plate Prices" intro="Choose one front or rear plate, or a front and rear pair. The same straightforward delivery rate is shown alongside every order." image="/images/styles/bevel.jpg">
    <section className="overflow-hidden rounded-[1.75rem] border border-white/90 bg-white/80 shadow-[0_20px_55px_rgba(15,23,42,.08)]">
      <div className="flex flex-col gap-4 border-b border-slate-200 px-5 py-5 sm:flex-row sm:items-end sm:justify-between sm:px-7"><div><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#c89612]">Plate finishes</p><h2 className="mt-1 text-2xl font-black tracking-[-.04em]">One plate or a matching pair.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">Prices are per plate. The pair column is simply two plates — there is no pair discount.</p></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead className="bg-slate-950 text-white"><tr><th className="px-5 py-3 text-xs font-bold sm:px-7">Style</th><th className="px-5 py-3 text-right text-xs font-bold">One plate<br /><span className="font-medium text-slate-400">front or rear</span></th><th className="px-5 py-3 text-right text-xs font-bold sm:px-7">Front and rear pair<br /><span className="font-medium text-slate-400">two plates</span></th></tr></thead><tbody>{prices.map(([name, href, single, pair], index) => <tr key={name} className="border-t border-slate-200 transition hover:bg-[#f3c544]/[.05]"><td className="px-5 py-4 sm:px-7"><Link href={href} className="font-bold text-slate-900 hover:text-[#9a7410]">{name}</Link>{index === 0 && <span className="ml-2 rounded-full bg-[#f3c544]/15 px-2 py-1 text-[9px] font-black uppercase tracking-[.12em] text-[#9a7410]">from</span>}</td><td className="px-5 py-4 text-right text-lg font-black tracking-[-.04em] text-slate-950">{single}</td><td className="px-5 py-4 text-right text-lg font-black tracking-[-.04em] text-slate-950 sm:px-7">{pair}</td></tr>)}</tbody></table></div>
    </section>

    <section className="mt-4 grid gap-4 lg:grid-cols-[.92fr_1.08fr]">
      <div className="rounded-[1.75rem] bg-[#080c14] p-5 text-white shadow-xl sm:p-7"><Truck className="h-5 w-5 text-[#f3c544]" /><p className="mt-4 text-[10px] font-black uppercase tracking-[.17em] text-[#f3c544]">Delivery charges</p><h2 className="mt-1 text-2xl font-black tracking-[-.04em]">Simple delivery, shown before you pay.</h2><p className="mt-3 text-sm leading-6 text-slate-300">Royal Mail First Class is £3 for goods orders under £15 and free for orders of £15 or more. Tracked 24 is an additional £2. Delivery times are aims, not guarantees.</p><div className="mt-5 grid grid-cols-2 gap-2 text-xs"><div className="rounded-2xl border border-white/10 bg-white/[.06] p-3"><span className="text-slate-400">Under £15</span><strong className="mt-1 block text-base">£3 / £5 tracked</strong></div><div className="rounded-2xl border border-white/10 bg-white/[.06] p-3"><span className="text-slate-400">£15 or more</span><strong className="mt-1 block text-base">Free / £2 tracked</strong></div></div></div>
      <div className="rounded-[1.75rem] border border-[#f3c544]/30 bg-[#f3c544]/10 p-5 sm:p-7"><Package className="h-5 w-5 text-[#9a7410]" /><h2 className="mt-4 text-2xl font-black tracking-[-.04em]">What that looks like in practice.</h2><div className="mt-5 grid gap-2 sm:grid-cols-2"><div className="rounded-2xl bg-white/70 p-4"><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#9a7410]">One Standard plate</p><p className="mt-2 text-sm text-slate-600">£12.49 goods</p><p className="mt-1 font-black">£15.49 First Class</p><p className="text-xs text-slate-500">£17.49 with Tracked 24</p></div><div className="rounded-2xl bg-white/70 p-4"><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#9a7410]">Standard pair</p><p className="mt-2 text-sm text-slate-600">£24.98 goods</p><p className="mt-1 font-black">£24.98 First Class</p><p className="text-xs text-slate-500">£26.98 with Tracked 24</p></div></div><p className="mt-5 text-sm leading-6 text-slate-700">Orders of exactly £15 qualify for free First Class. Collection from Castleview Gardens, Ilford, IG1 3QF has no delivery charge.</p></div>
    </section>

    <section className="mt-4 rounded-[1.75rem] border border-white/90 bg-white/75 p-5 sm:p-7"><div className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#c89612]">Before you pay</p><h2 className="mt-1 text-xl font-black tracking-[-.035em]">Check the details you enter.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Motorcycle, oversized plates and any badge or option are priced in the plate builder. Your plates are made to the details you enter. You can cancel for a full refund at any time before production starts.</p><div className="mt-4 flex flex-wrap gap-3 text-xs font-semibold text-slate-600"><span className="inline-flex items-center gap-1.5"><Check className="h-4 w-4 text-[#c89612]" /> Delivery shown in basket</span><span className="inline-flex items-center gap-1.5"><ShieldCheck className="h-4 w-4 text-[#c89612]" /> Clear running total</span></div></div><div className="flex flex-wrap gap-2"><PageLink href="/#configurator">Build your plates</PageLink><PageLink href="/delivery" light>Delivery details</PageLink></div></div><p className="mt-5 text-xs leading-5 text-slate-500">For the Ghost finish, read the <InlinePageLink href="/ghost-number-plates">Ghost page</InlinePageLink> before ordering. See <InlinePageLink href="/returns">returns and cancellations</InlinePageLink> and our guide to <InlinePageLink href="/guides/replacement-number-plate-cost-what-changes-the-price">what changes the price</InlinePageLink>.</p></section>
  </EssentialPageShell>;
}
