import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CarFront, CheckCircle2, FileCheck2, PackageCheck, Sparkles, Truck } from "lucide-react";
import EssentialPageShell, { InlinePageLink, PageLink } from "@/components/EssentialPageShell";

export const metadata: Metadata = { title: "How It Works | ReplacementPlates", description: "How ordering number plates from ReplacementPlates works: build your plate, provide documents, we check, then delivery or collection." };

const steps = [
  ["1", "Build your plate", "Enter your registration, choose front, rear or a pair, and pick your style and size. The builder shows a preview and the price.", CarFront],
  ["2", "Place your order and provide your documents", "We need to check your identity and your entitlement to the registration. See the documents page for accepted documents.", FileCheck2],
  ["3", "We check, then make and supply your plates", "We do not supply road-use plates until our required checks are complete. Once they are, your plates are made to your order.", PackageCheck],
  ["4", "Delivery or collection", "Choose Royal Mail delivery or collection from Castleview Gardens, Ilford, IG1 3QF. Please confirm before travelling.", Truck],
] as const;

export default function HowItWorksPage() {
  return (
    <EssentialPageShell eyebrow="The ordering journey" title="How It Works" intro="Build your plate, provide your documents, let us complete the required checks, then choose Royal Mail delivery or confirmed collection." image="/images/styles/4d.jpg">
      <div className="grid gap-3">{steps.map(([number, title, text, Icon], index) => <section key={number} className="relative overflow-hidden rounded-3xl border border-white/80 bg-white/75 p-5 shadow-[0_14px_36px_rgba(15,23,42,.06)] sm:p-6"><div className="absolute right-0 top-0 h-full w-1/3 opacity-[.07]"><Image src={index % 2 === 0 ? "/images/styles/standard.jpg" : "/images/styles/5d.jpg"} alt="" fill className="object-cover" sizes="33vw" /></div><div className="relative flex gap-4 sm:gap-6"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-slate-950 text-lg font-black text-[#f3c544]">{number}</span><div className="max-w-3xl"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-[#c89612]" /><h2 className="text-xl font-black tracking-[-.035em]">{title}</h2></div><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p>{index === 0 && <p className="mt-2 text-xs leading-5 text-slate-500">Not sure which style? See the <InlinePageLink href="/prices">price list</InlinePageLink> or start with <InlinePageLink href="/standard-number-plates">Standard plates</InlinePageLink>.</p>}{index === 1 && <p className="mt-2 text-xs leading-5 text-slate-500">We’ll tell you how to provide them when you order. <InlinePageLink href="/documents-you-need">View accepted documents</InlinePageLink>.</p>}{index === 2 && <p className="mt-2 text-xs leading-5 text-slate-500">You can cancel for a full refund at any time before production starts. See <InlinePageLink href="/returns">returns and cancellations</InlinePageLink>.</p>}{index === 3 && <div className="mt-3 flex flex-wrap gap-2 text-[11px] font-bold text-slate-700"><span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1.5"><CheckCircle2 className="h-3 w-3 text-emerald-600" /> First Class from £3</span><span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1.5"><CheckCircle2 className="h-3 w-3 text-emerald-600" /> Tracked 24 upgrade</span><span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1.5"><CheckCircle2 className="h-3 w-3 text-emerald-600" /> Ilford collection</span></div>}</div></div></section>)}</div>
      <section className="mt-4 grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center"><div className="rounded-3xl bg-[#0b1625] p-5 text-white shadow-xl sm:p-6"><div className="flex items-start gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#f3c544] text-slate-950"><Sparkles className="h-4 w-4" /></span><div><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#f3c544]">Full walkthrough</p><h2 className="mt-1 text-xl font-black">Want the detailed replacement guide?</h2><p className="mt-1.5 text-sm leading-5 text-slate-400">Read the step-by-step guide for replacing a number plate in the UK.</p></div></div></div><Link href="/guides/how-to-replace-a-number-plate-in-the-uk" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#f3c544] px-4 py-2.5 text-xs font-bold text-slate-950">Read the guide <ArrowRight className="h-3.5 w-3.5" /></Link></section>
      <section className="mt-4 rounded-3xl border border-[#f3c544]/30 bg-[#f3c544]/10 p-5 sm:p-6"><h2 className="text-lg font-black">If something isn’t right</h2><p className="mt-2 text-sm leading-6 text-slate-700">Contact <a className="font-bold underline underline-offset-4" href="mailto:info@replacementplates.uk">info@replacementplates.uk</a>, telephone 020 3576 6603 or WhatsApp +44 7754 185366. See <InlinePageLink href="/returns">returns and cancellations</InlinePageLink> and <InlinePageLink href="/warranty">faulty plates and warranty</InlinePageLink>.</p><div className="mt-4 flex flex-wrap gap-2"><PageLink href="/#configurator">Build your plates</PageLink><PageLink href="/contact" light>Contact us</PageLink></div></section>
    </EssentialPageShell>
  );
}
