import type { Metadata } from "next";
import { ChevronDown, CircleHelp, FileCheck2, PackageCheck, ShieldCheck } from "lucide-react";
import EssentialPageShell, { InlinePageLink, PageLink } from "@/components/EssentialPageShell";

export const metadata: Metadata = { title: "Number Plate FAQs | ReplacementPlates", description: "Answers to common questions about ordering, documents, delivery charges, collection, legal requirements, cancellation, warranty and faulty plates." };

const groups = [
  { title: "Ordering", icon: CircleHelp, items: [["How much do number plates cost?", <>From £12.49 for one Standard plate. A pair is a front and a rear plate. See the <InlinePageLink href="/prices">price list</InlinePageLink>.</>], ["Can I order just one plate?", "Yes. Order a single front or rear plate, or a pair."], ["Can I change my order after I’ve placed it?", <>Contact us straight away. You can ask for an amendment within 2 hours of placing your order. It isn’t guaranteed and we’ll tell you of any cost first. This does not affect your right to cancel before production starts. See the <InlinePageLink href="/terms">terms</InlinePageLink>.</>]] },
  { title: "Documents", icon: FileCheck2, items: [["What documents do I need?", "Proof of your name and address, and proof you can use the registration. See documents you need."], ["Can I use my passport?", "A passport confirms your name only, so you also need a document that shows your address, such as a driving licence or a recent utility or bank statement."], ["Why do you need to check my documents?", "The DVLA requires a registered supplier to check identity and entitlement before supplying road-use plates. See legal number plates for the requirements."]] },
  { title: "Delivery and collection", icon: PackageCheck, items: [["How much is delivery?", <>Standard Royal Mail First Class delivery is £3 on orders under £15 and free on orders of £15 or more. Upgrade to Royal Mail Tracked 24 for an additional £2. Royal Mail delivery times are aims, not guarantees. See <InlinePageLink href="/delivery">delivery and dispatch</InlinePageLink>.</>], ["When will my order be dispatched?", "If your order and document checks are complete before 2pm on a working weekday, we aim to dispatch it that day. Delivery times are Royal Mail’s aims."], ["Where do you deliver?", <>We deliver by Royal Mail to addresses in Great Britain. For Northern Ireland, the Channel Islands or the Isle of Man, please <InlinePageLink href="/contact">contact us before ordering</InlinePageLink>.</>], ["Can I collect my plates?", "Yes, from Castleview Gardens, Ilford, IG1 3QF. Ready within 3 hours, subject to WhatsApp confirmation. Please confirm before travelling."], ["Do you have a shop near me?", <>We have one collection location, in Ilford. We do not have shops or branches elsewhere. See <InlinePageLink href="/areas-we-cover">areas we cover</InlinePageLink>.</>]] },
  { title: "Legal", icon: ShieldCheck, items: [["Are your plates road legal?", "Each product page explains the finish and its legal information. Road-use plates are intended to meet legal requirements, and where a style or format needs additional checks, its page says so. Ghost compliance information is being finalised."], ["Will my plates pass an MOT?", "Correctly made plates can still fail if they are damaged, dirty, obscured or insecurely fitted. The MOT checks a plate’s condition, legibility and format. Supplier and British Standard markings are required by law even though the MOT does not check them."]] },
  { title: "Cancellation, warranty and problems", icon: ShieldCheck, items: [["Can I cancel my order?", <>You can cancel for a full refund at any time before production starts. No cancellation or administration fee applies. Once production starts, personalised plates cannot normally be cancelled for a change of mind. Your statutory rights are unaffected. See the <InlinePageLink href="/terms">terms</InlinePageLink> or <InlinePageLink href="/contact">contact us</InlinePageLink> as soon as possible.</>], ["Is there a warranty?", "New orders carry a manufacturing-defect warranty: 6 months for Standard, 3D Gel and 4D, and 12 months for 5D, Ghost and Bevel, starting on delivery or collection. It is in addition to your statutory rights."], ["What if my plate is faulty?", "Contact us with your order number. Photos help if you can take them, but are not required to make a claim; if you cannot provide them, we will arrange another way to assess the plate. There is no 24-hour reporting deadline that removes your statutory rights."], ["My plates were stolen. What should I do?", "Contact the police. If you receive a fine or charge you are not responsible for, your registration may have been cloned: tell the police and contact the organisation that sent the notice, following its process and deadline. Keep your evidence."]] },
] as const;

export default function FaqsPage() {
  return <EssentialPageShell eyebrow="Answers before you order" title="Number Plate FAQs" intro="Helpful answers on pricing, documents, delivery, collection, legal requirements, cancellations and faults." image="/images/styles/4d.jpg">
    <section className="grid gap-4 lg:grid-cols-[.74fr_1.26fr]"><aside className="rounded-[1.75rem] bg-[#080c14] p-5 text-white shadow-xl sm:p-7 lg:sticky lg:top-24 lg:self-start"><CircleHelp className="h-6 w-6 text-[#f3c544]" /><p className="mt-5 text-[10px] font-black uppercase tracking-[.17em] text-[#f3c544]">A quick answer</p><h2 className="mt-1 text-2xl font-black tracking-[-.04em]">Clear before you build.</h2><p className="mt-3 text-sm leading-6 text-slate-300">One £12.49 Standard plate with First Class delivery is £15.49 in total. A £24.98 Standard pair qualifies for free First Class, or £26.98 with Tracked 24.</p><div className="mt-6 border-t border-white/10 pt-5"><p className="text-sm font-bold">Still need help?</p><p className="mt-1 text-xs leading-5 text-slate-400">Email, call or WhatsApp us with your question and, where relevant, your order number.</p><div className="mt-4 flex flex-wrap gap-2"><PageLink href="/contact">Contact us</PageLink><PageLink href="/how-it-works" light>How it works</PageLink></div></div></aside>
      <div className="space-y-4">{groups.map(({ title, icon: Icon, items }) => <section key={title} className="overflow-hidden rounded-[1.75rem] border border-white/90 bg-white/80 shadow-[0_16px_40px_rgba(15,23,42,.06)]"><div className="flex items-center gap-3 border-b border-slate-200 px-5 py-4 sm:px-6"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f3c544]/15 text-[#9a7410]"><Icon className="h-4 w-4" /></span><h2 className="text-lg font-black tracking-[-.03em]">{title}</h2></div>{items.map(([question, answer], index) => <details key={question} className="group border-b border-slate-200 last:border-0"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-4 text-sm font-bold text-slate-900 [&::-webkit-details-marker]:hidden sm:px-6"><span><span className="mr-3 text-[10px] font-black tracking-[.14em] text-[#c89612]">{String(index + 1).padStart(2, "0")}</span>{question}</span><ChevronDown className="h-4 w-4 shrink-0 text-[#c89612] transition group-open:rotate-180" /></summary><div className="px-5 pb-5 text-sm leading-6 text-slate-600 sm:px-6">{answer}</div></details>)}</section>)}</div>
    </section>
    <section className="mt-4 rounded-[1.75rem] border border-[#f3c544]/30 bg-[#f3c544]/10 p-5 sm:p-7"><h2 className="text-xl font-black tracking-[-.035em]">Useful next reads</h2><p className="mt-2 text-sm leading-6 text-slate-700">Read more about documents, replacement plates, vehicle cloning, MOT checks, UK number-plate rules, fonts, EV green flash, registration plates, enforcement, size, and comparing sellers in our guides.</p><div className="mt-4 flex flex-wrap gap-2"><PageLink href="/prices">Price list</PageLink><PageLink href="/delivery" light>Delivery and dispatch</PageLink><PageLink href="/areas-we-cover" light>Areas we cover</PageLink></div></section>
  </EssentialPageShell>;
}
